/* IMPORTANT
 * This snapshot file is auto-generated, but designed for humans.
 * It should be checked into source control and tracked carefully.
 * Re-generate by setting TAP_SNAPSHOT=1 and running tests.
 * Make sure to inspect the output below.  Do not ignore changes!
 */
'use strict'
exports[`test/ttl.ts > TAP > tests using Date.now() > set item pre-stale > dump with stale values 1`] = `
Array [
  Array [
    1,
    Object {
      "start": 3316,
      "ttl": 10,
      "value": 1,
    },
  ],
  Array [
    2,
    Object {
      "start": 3305,
      "ttl": 10,
      "value": 2,
    },
  ],
]
`

exports[`test/ttl.ts > TAP > tests using Date.now() > ttl on set, not on cache > status updates 1`] = `
Array [
  Object {
    "key": 1,
    "now": 2259,
    "op": "set",
    "remainingTTL": 10,
    "set": "add",
    "start": 2259,
    "ttl": 10,
    "value": 1,
  },
  Object {
    "get": "hit",
    "key": 1,
    "now": 2259,
    "op": "get",
    "remainingTTL": 10,
    "start": 2259,
    "ttl": 10,
    "value": 1,
  },
  Object {
    "get": "hit",
    "key": 1,
    "now": 2264,
    "op": "get",
    "remainingTTL": 5,
    "start": 2259,
    "ttl": 10,
    "value": 1,
  },
  Object {
    "get": "hit",
    "key": 1,
    "now": 2269,
    "op": "get",
    "remainingTTL": 0,
    "start": 2259,
    "ttl": 10,
    "value": 1,
  },
  Object {
    "has": "stale",
    "key": 1,
    "now": 2270,
    "op": "has",
    "remainingTTL": -1,
    "start": 2259,
    "ttl": 10,
  },
  Object {
    "get": "stale",
    "key": 1,
    "now": 2270,
    "op": "get",
    "remainingTTL": -1,
    "start": 2259,
    "ttl": 10,
  },
  Object {
    "key": 2,
    "now": 2270,
    "op": "set",
    "remainingTTL": 100,
    "set": "add",
    "start": 2270,
    "ttl": 100,
    "value": 2,
  },
  Object {
    "has": "hit",
    "key": 2,
    "now": 2320,
    "op": "has",
    "remainingTTL": 50,
    "start": 2270,
    "ttl": 100,
  },
  Object {
    "get": "hit",
    "key": 2,
    "now": 2320,
    "op": "get",
    "remainingTTL": 50,
    "start": 2270,
    "ttl": 100,
    "value": 2,
  },
  Object {
    "has": "stale",
    "key": 2,
    "now": 2371,
    "op": "has",
    "remainingTTL": -1,
    "start": 2270,
    "ttl": 100,
  },
  Object {
    "get": "stale",
    "key": 2,
    "now": 2371,
    "op": "get",
    "remainingTTL": -1,
    "start": 2270,
    "ttl": 100,
  },
  Object {
    "key": 0,
    "now": 2371,
    "op": "set",
    "remainingTTL": 10,
    "set": "add",
    "start": 2371,
    "ttl": 10,
    "value": 0,
  },
  Object {
    "key": 1,
    "now": 2371,
    "op": "set",
    "remainingTTL": 10,
    "set": "add",
    "start": 2371,
    "ttl": 10,
    "value": 1,
  },
  Object {
    "key": 2,
    "now": 2371,
    "op": "set",
    "remainingTTL": 10,
    "set": "add",
    "start": 2371,
    "ttl": 10,
    "value": 2,
  },
  Object {
    "key": 3,
    "now": 2371,
    "op": "set",
    "remainingTTL": 10,
    "set": "add",
    "start": 2371,
    "ttl": 10,
    "value": 3,
  },
  Object {
    "key": 4,
    "now": 2371,
    "op": "set",
    "remainingTTL": 10,
    "set": "add",
    "start": 2371,
    "ttl": 10,
    "value": 4,
  },
  Object {
    "key": 5,
    "now": 2371,
    "op": "set",
    "remainingTTL": 10,
    "set": "add",
    "start": 2371,
    "ttl": 10,
    "value": 5,
  },
  Object {
    "key": 6,
    "now": 2371,
    "op": "set",
    "remainingTTL": 10,
    "set": "add",
    "start": 2371,
    "ttl": 10,
    "value": 6,
  },
  Object {
    "key": 7,
    "now": 2371,
    "op": "set",
    "remainingTTL": 10,
    "set": "add",
    "start": 2371,
    "ttl": 10,
    "value": 7,
  },
  Object {
    "key": 8,
    "now": 2371,
    "op": "set",
    "remainingTTL": 10,
    "set": "add",
    "start": 2371,
    "ttl": 10,
    "value": 8,
  },
  Object {
    "has": "stale",
    "key": 4,
    "now": 2382,
    "op": "has",
    "remainingTTL": -1,
    "start": 2371,
    "ttl": 10,
  },
  Object {
    "get": "stale",
    "key": 4,
    "now": 2382,
    "op": "get",
    "remainingTTL": -1,
    "start": 2371,
    "ttl": 10,
  },
]
`

exports[`test/ttl.ts > TAP > tests using Date.now() > ttl tests defaults > status updates 1`] = `
Array [
  Object {
    "key": 1,
    "now": 1812,
    "op": "set",
    "remainingTTL": 10,
    "set": "add",
    "start": 1812,
    "ttl": 10,
    "value": 1,
  },
  Object {
    "get": "hit",
    "key": 1,
    "now": 1812,
    "op": "get",
    "remainingTTL": 10,
    "start": 1812,
    "ttl": 10,
    "value": 1,
  },
  Object {
    "get": "hit",
    "key": 1,
    "now": 1817,
    "op": "get",
    "remainingTTL": 5,
    "start": 1812,
    "ttl": 10,
    "value": 1,
  },
  Object {
    "get": "hit",
    "key": 1,
    "now": 1822,
    "op": "get",
    "remainingTTL": 0,
    "start": 1812,
    "ttl": 10,
    "value": 1,
  },
  Object {
    "has": "stale",
    "key": 1,
    "now": 1824,
    "op": "has",
    "remainingTTL": -2,
    "start": 1812,
    "ttl": 10,
  },
  Object {
    "get": "stale",
    "key": 1,
    "now": 1824,
    "op": "get",
    "remainingTTL": -2,
    "start": 1812,
    "ttl": 10,
  },
  Object {
    "has": "hit",
    "key": 2,
    "now": 1874,
    "op": "has",
    "remainingTTL": 50,
    "start": 1824,
    "ttl": 100,
  },
  Object {
    "get": "hit",
    "key": 2,
    "now": 1874,
    "op": "get",
    "remainingTTL": 50,
    "start": 1824,
    "ttl": 100,
    "value": 2,
  },
  Object {
    "get": "stale",
    "key": 2,
    "now": 1925,
    "op": "get",
    "remainingTTL": -1,
    "start": 1824,
    "ttl": 100,
  },
  Object {
    "key": 0,
    "now": 1925,
    "op": "set",
    "remainingTTL": 10,
    "set": "add",
    "start": 1925,
    "ttl": 10,
    "value": 0,
  },
  Object {
    "key": 1,
    "now": 1925,
    "op": "set",
    "remainingTTL": 10,
    "set": "add",
    "start": 1925,
    "ttl": 10,
    "value": 1,
  },
  Object {
    "key": 2,
    "now": 1925,
    "op": "set",
    "remainingTTL": 10,
    "set": "add",
    "start": 1925,
    "ttl": 10,
    "value": 2,
  },
  Object {
    "key": 3,
    "now": 1925,
    "op": "set",
    "remainingTTL": 10,
    "set": "add",
    "start": 1925,
    "ttl": 10,
    "value": 3,
  },
  Object {
    "key": 4,
    "now": 1925,
    "op": "set",
    "remainingTTL": 10,
    "set": "add",
    "start": 1925,
    "ttl": 10,
    "value": 4,
  },
  Object {
    "key": 5,
    "now": 1925,
    "op": "set",
    "remainingTTL": 10,
    "set": "add",
    "start": 1925,
    "ttl": 10,
    "value": 5,
  },
  Object {
    "key": 6,
    "now": 1925,
    "op": "set",
    "remainingTTL": 10,
    "set": "add",
    "start": 1925,
    "ttl": 10,
    "value": 6,
  },
  Object {
    "key": 7,
    "now": 1925,
    "op": "set",
    "remainingTTL": 10,
    "set": "add",
    "start": 1925,
    "ttl": 10,
    "value": 7,
  },
  Object {
    "key": 8,
    "now": 1925,
    "op": "set",
    "remainingTTL": 10,
    "set": "add",
    "start": 1925,
    "ttl": 10,
    "value": 8,
  },
  Object {
    "has": "stale",
    "key": 4,
    "now": 1936,
    "op": "has",
    "remainingTTL": -1,
    "start": 1925,
    "ttl": 10,
  },
  Object {
    "get": "stale",
    "key": 4,
    "now": 1936,
    "op": "get",
    "remainingTTL": -1,
    "start": 1925,
    "ttl": 10,
  },
  Object {
    "get": "hit",
    "key": "immortal",
    "op": "get",
    "value": true,
  },
  Object {
    "get": "hit",
    "key": "immortal",
    "op": "get",
    "value": true,
  },
]
`

exports[`test/ttl.ts > TAP > tests using Date.now() > ttl tests with ttlResolution=100 > status updates 1`] = `
Array [
  Object {
    "key": 1,
    "now": 2136,
    "op": "set",
    "remainingTTL": 10,
    "set": "add",
    "start": 2136,
    "ttl": 10,
    "value": 1,
  },
  Object {
    "get": "hit",
    "key": 1,
    "now": 2136,
    "op": "get",
    "remainingTTL": 10,
    "start": 2136,
    "ttl": 10,
    "value": 1,
  },
  Object {
    "get": "hit",
    "key": 1,
    "now": 2136,
    "op": "get",
    "remainingTTL": 10,
    "start": 2136,
    "ttl": 10,
    "value": 1,
  },
  Object {
    "get": "hit",
    "key": 1,
    "now": 2136,
    "op": "get",
    "remainingTTL": 10,
    "start": 2136,
    "ttl": 10,
    "value": 1,
  },
  Object {
    "has": "hit",
    "key": 1,
    "now": 2136,
    "op": "has",
    "remainingTTL": 10,
    "start": 2136,
    "ttl": 10,
  },
  Object {
    "get": "hit",
    "key": 1,
    "now": 2136,
    "op": "get",
    "remainingTTL": 10,
    "start": 2136,
    "ttl": 10,
    "value": 1,
  },
  Object {
    "has": "stale",
    "key": 1,
    "now": 2247,
    "op": "has",
    "remainingTTL": -101,
    "start": 2136,
    "ttl": 10,
  },
  Object {
    "get": "stale",
    "key": 1,
    "now": 2247,
    "op": "get",
    "remainingTTL": -101,
    "start": 2136,
    "ttl": 10,
  },
]
`

exports[`test/ttl.ts > TAP > tests using Date.now() > ttlAutopurge > status updates 1`] = `
Array [
  Object {
    "key": 1,
    "now": 2247,
    "op": "set",
    "remainingTTL": 10,
    "set": "add",
    "start": 2247,
    "ttl": 10,
    "value": 1,
  },
  Object {
    "key": 2,
    "now": 2247,
    "op": "set",
    "remainingTTL": 10,
    "set": "add",
    "start": 2247,
    "ttl": 10,
    "value": 2,
  },
  Object {
    "key": 2,
    "now": 2247,
    "oldValue": 2,
    "op": "set",
    "remainingTTL": 11,
    "set": "replace",
    "start": 2247,
    "ttl": 11,
    "value": 3,
  },
]
`

exports[`test/ttl.ts > TAP > tests with performance.now() > set item pre-stale > dump with stale values 1`] = `
Array [
  Array [
    1,
    Object {
      "start": 1506,
      "ttl": 10,
      "value": 1,
    },
  ],
  Array [
    2,
    Object {
      "start": 1495,
      "ttl": 10,
      "value": 2,
    },
  ],
]
`

exports[`test/ttl.ts > TAP > tests with performance.now() > ttl on set, not on cache > status updates 1`] = `
Array [
  Object {
    "key": 1,
    "now": 449,
    "op": "set",
    "remainingTTL": 10,
    "set": "add",
    "start": 449,
    "ttl": 10,
    "value": 1,
  },
  Object {
    "get": "hit",
    "key": 1,
    "now": 449,
    "op": "get",
    "remainingTTL": 10,
    "start": 449,
    "ttl": 10,
    "value": 1,
  },
  Object {
    "get": "hit",
    "key": 1,
    "now": 454,
    "op": "get",
    "remainingTTL": 5,
    "start": 449,
    "ttl": 10,
    "value": 1,
  },
  Object {
    "get": "hit",
    "key": 1,
    "now": 459,
    "op": "get",
    "remainingTTL": 0,
    "start": 449,
    "ttl": 10,
    "value": 1,
  },
  Object {
    "has": "stale",
    "key": 1,
    "now": 460,
    "op": "has",
    "remainingTTL": -1,
    "start": 449,
    "ttl": 10,
  },
  Object {
    "get": "stale",
    "key": 1,
    "now": 460,
    "op": "get",
    "remainingTTL": -1,
    "start": 449,
    "ttl": 10,
  },
  Object {
    "key": 2,
    "now": 460,
    "op": "set",
    "remainingTTL": 100,
    "set": "add",
    "start": 460,
    "ttl": 100,
    "value": 2,
  },
  Object {
    "has": "hit",
    "key": 2,
    "now": 510,
    "op": "has",
    "remainingTTL": 50,
    "start": 460,
    "ttl": 100,
  },
  Object {
    "get": "hit",
    "key": 2,
    "now": 510,
    "op": "get",
    "remainingTTL": 50,
    "start": 460,
    "ttl": 100,
    "value": 2,
  },
  Object {
    "has": "stale",
    "key": 2,
    "now": 561,
    "op": "has",
    "remainingTTL": -1,
    "start": 460,
    "ttl": 100,
  },
  Object {
    "get": "stale",
    "key": 2,
    "now": 561,
    "op": "get",
    "remainingTTL": -1,
    "start": 460,
    "ttl": 100,
  },
  Object {
    "key": 0,
    "now": 561,
    "op": "set",
    "remainingTTL": 10,
    "set": "add",
    "start": 561,
    "ttl": 10,
    "value": 0,
  },
  Object {
    "key": 1,
    "now": 561,
    "op": "set",
    "remainingTTL": 10,
    "set": "add",
    "start": 561,
    "ttl": 10,
    "value": 1,
  },
  Object {
    "key": 2,
    "now": 561,
    "op": "set",
    "remainingTTL": 10,
    "set": "add",
    "start": 561,
    "ttl": 10,
    "value": 2,
  },
  Object {
    "key": 3,
    "now": 561,
    "op": "set",
    "remainingTTL": 10,
    "set": "add",
    "start": 561,
    "ttl": 10,
    "value": 3,
  },
  Object {
    "key": 4,
    "now": 561,
    "op": "set",
    "remainingTTL": 10,
    "set": "add",
    "start": 561,
    "ttl": 10,
    "value": 4,
  },
  Object {
    "key": 5,
    "now": 561,
    "op": "set",
    "remainingTTL": 10,
    "set": "add",
    "start": 561,
    "ttl": 10,
    "value": 5,
  },
  Object {
    "key": 6,
    "now": 561,
    "op": "set",
    "remainingTTL": 10,
    "set": "add",
    "start": 561,
    "ttl": 10,
    "value": 6,
  },
  Object {
    "key": 7,
    "now": 561,
    "op": "set",
    "remainingTTL": 10,
    "set": "add",
    "start": 561,
    "ttl": 10,
    "value": 7,
  },
  Object {
    "key": 8,
    "now": 561,
    "op": "set",
    "remainingTTL": 10,
    "set": "add",
    "start": 561,
    "ttl": 10,
    "value": 8,
  },
  Object {
    "has": "stale",
    "key": 4,
    "now": 572,
    "op": "has",
    "remainingTTL": -1,
    "start": 561,
    "ttl": 10,
  },
  Object {
    "get": "stale",
    "key": 4,
    "now": 572,
    "op": "get",
    "remainingTTL": -1,
    "start": 561,
    "ttl": 10,
  },
]
`

exports[`test/ttl.ts > TAP > tests with performance.now() > ttl tests defaults > status updates 1`] = `
Array [
  Object {
    "key": 1,
    "now": 2,
    "op": "set",
    "remainingTTL": 10,
    "set": "add",
    "start": 2,
    "ttl": 10,
    "value": 1,
  },
  Object {
    "get": "hit",
    "key": 1,
    "now": 2,
    "op": "get",
    "remainingTTL": 10,
    "start": 2,
    "ttl": 10,
    "value": 1,
  },
  Object {
    "get": "hit",
    "key": 1,
    "now": 7,
    "op": "get",
    "remainingTTL": 5,
    "start": 2,
    "ttl": 10,
    "value": 1,
  },
  Object {
    "get": "hit",
    "key": 1,
    "now": 12,
    "op": "get",
    "remainingTTL": 0,
    "start": 2,
    "ttl": 10,
    "value": 1,
  },
  Object {
    "has": "stale",
    "key": 1,
    "now": 14,
    "op": "has",
    "remainingTTL": -2,
    "start": 2,
    "ttl": 10,
  },
  Object {
    "get": "stale",
    "key": 1,
    "now": 14,
    "op": "get",
    "remainingTTL": -2,
    "start": 2,
    "ttl": 10,
  },
  Object {
    "has": "hit",
    "key": 2,
    "now": 64,
    "op": "has",
    "remainingTTL": 50,
    "start": 14,
    "ttl": 100,
  },
  Object {
    "get": "hit",
    "key": 2,
    "now": 64,
    "op": "get",
    "remainingTTL": 50,
    "start": 14,
    "ttl": 100,
    "value": 2,
  },
  Object {
    "get": "stale",
    "key": 2,
    "now": 115,
    "op": "get",
    "remainingTTL": -1,
    "start": 14,
    "ttl": 100,
  },
  Object {
    "key": 0,
    "now": 115,
    "op": "set",
    "remainingTTL": 10,
    "set": "add",
    "start": 115,
    "ttl": 10,
    "value": 0,
  },
  Object {
    "key": 1,
    "now": 115,
    "op": "set",
    "remainingTTL": 10,
    "set": "add",
    "start": 115,
    "ttl": 10,
    "value": 1,
  },
  Object {
    "key": 2,
    "now": 115,
    "op": "set",
    "remainingTTL": 10,
    "set": "add",
    "start": 115,
    "ttl": 10,
    "value": 2,
  },
  Object {
    "key": 3,
    "now": 115,
    "op": "set",
    "remainingTTL": 10,
    "set": "add",
    "start": 115,
    "ttl": 10,
    "value": 3,
  },
  Object {
    "key": 4,
    "now": 115,
    "op": "set",
    "remainingTTL": 10,
    "set": "add",
    "start": 115,
    "ttl": 10,
    "value": 4,
  },
  Object {
    "key": 5,
    "now": 115,
    "op": "set",
    "remainingTTL": 10,
    "set": "add",
    "start": 115,
    "ttl": 10,
    "value": 5,
  },
  Object {
    "key": 6,
    "now": 115,
    "op": "set",
    "remainingTTL": 10,
    "set": "add",
    "start": 115,
    "ttl": 10,
    "value": 6,
  },
  Object {
    "key": 7,
    "now": 115,
    "op": "set",
    "remainingTTL": 10,
    "set": "add",
    "start": 115,
    "ttl": 10,
    "value": 7,
  },
  Object {
    "key": 8,
    "now": 115,
    "op": "set",
    "remainingTTL": 10,
    "set": "add",
    "start": 115,
    "ttl": 10,
    "value": 8,
  },
  Object {
    "has": "stale",
    "key": 4,
    "now": 126,
    "op": "has",
    "remainingTTL": -1,
    "start": 115,
    "ttl": 10,
  },
  Object {
    "get": "stale",
    "key": 4,
    "now": 126,
    "op": "get",
    "remainingTTL": -1,
    "start": 115,
    "ttl": 10,
  },
  Object {
    "get": "hit",
    "key": "immortal",
    "op": "get",
    "value": true,
  },
  Object {
    "get": "hit",
    "key": "immortal",
    "op": "get",
    "value": true,
  },
]
`

exports[`test/ttl.ts > TAP > tests with performance.now() > ttl tests with ttlResolution=100 > status updates 1`] = `
Array [
  Object {
    "key": 1,
    "now": 326,
    "op": "set",
    "remainingTTL": 10,
    "set": "add",
    "start": 326,
    "ttl": 10,
    "value": 1,
  },
  Object {
    "get": "hit",
    "key": 1,
    "now": 326,
    "op": "get",
    "remainingTTL": 10,
    "start": 326,
    "ttl": 10,
    "value": 1,
  },
  Object {
    "get": "hit",
    "key": 1,
    "now": 326,
    "op": "get",
    "remainingTTL": 10,
    "start": 326,
    "ttl": 10,
    "value": 1,
  },
  Object {
    "get": "hit",
    "key": 1,
    "now": 326,
    "op": "get",
    "remainingTTL": 10,
    "start": 326,
    "ttl": 10,
    "value": 1,
  },
  Object {
    "has": "hit",
    "key": 1,
    "now": 326,
    "op": "has",
    "remainingTTL": 10,
    "start": 326,
    "ttl": 10,
  },
  Object {
    "get": "hit",
    "key": 1,
    "now": 326,
    "op": "get",
    "remainingTTL": 10,
    "start": 326,
    "ttl": 10,
    "value": 1,
  },
  Object {
    "has": "stale",
    "key": 1,
    "now": 437,
    "op": "has",
    "remainingTTL": -101,
    "start": 326,
    "ttl": 10,
  },
  Object {
    "get": "stale",
    "key": 1,
    "now": 437,
    "op": "get",
    "remainingTTL": -101,
    "start": 326,
    "ttl": 10,
  },
]
`

exports[`test/ttl.ts > TAP > tests with performance.now() > ttlAutopurge > status updates 1`] = `
Array [
  Object {
    "key": 1,
    "now": 437,
    "op": "set",
    "remainingTTL": 10,
    "set": "add",
    "start": 437,
    "ttl": 10,
    "value": 1,
  },
  Object {
    "key": 2,
    "now": 437,
    "op": "set",
    "remainingTTL": 10,
    "set": "add",
    "start": 437,
    "ttl": 10,
    "value": 2,
  },
  Object {
    "key": 2,
    "now": 437,
    "oldValue": 2,
    "op": "set",
    "remainingTTL": 11,
    "set": "replace",
    "start": 437,
    "ttl": 11,
    "value": 3,
  },
]
`
